[project]
name = "curvant-ml"
version = "0.0.0.a1"
description = "ML framework for predicting risky driving behavior on road curves using vehicular sensor data"
requires-python = ">=3.10"

dependencies = [
    "huggingface-hub",
    "scipy",
    "matplotlib",
    "plotly",
    "seaborn",
    "pandas",
    "numpy",
    "scikit-learn",
    "xgboost",
    "imbalanced-learn",
    "tensorflow",
    "pyyaml",
    "pyarrow",
    "optuna>=3.0",
    "torch>=2.0"
]

[project.optional-dependencies]
dev = ["jupyter", "ipykernel", "nbformat"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*", "utils*", "graphics*"]
