# -*- coding: utf-8 -*-
"""Tratamento_dos_Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yp06ZytB9MdgL3AGmFop6LzhUlkVGPPc

# 🚗🚚🚙🚍**CurvantML: Previsão de Condução de Risco em Curvas**
"""

from huggingface_hub import login, list_repo_files, hf_hub_download
from scipy.interpolate import make_interp_spline
from scipy.ndimage import gaussian_filter1d
import matplotlib.ticker as ticker
from mpl_toolkits.mplot3d import Axes3D
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import requests
import math
import os
import folium

plt.rcParams.update({'font.size': 12}) # Ajusta o tamanho da fonte das imagens para 12

"""##📂Carregando os dados, que estão no [Huggingface](https://huggingface.co/datasets/jwsouza13/routes_ML_inmetro/tree/main)🤗

São os dados brutos!
"""

global dir_hf
login(token='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')
dir_hf = 'jwsouza13/routes_ML_inmetro'

def load_data_folder(folder):
    """
    Baixa todos os arquivos de uma pasta específica em um dataset do Hugging Face.
    folder: ELETRONUCLEAR, SERRA, RJ-DF, RJ-MG-BA, JANEIRO
    """
    # todos os arquivos no dataset
    all_files = list_repo_files(repo_id=dir_hf, repo_type='dataset', token=True)
    folder_files = [f for f in all_files if f.startswith('DATASET-'+folder + "/") and f.endswith('.csv')]
    downloaded_files = []

    for file in folder_files:
        local_path = hf_hub_download(
            repo_id=dir_hf,
            filename=file,
            repo_type='dataset',
            token=True)
        downloaded_files.append(local_path)

    return downloaded_files

data_eletro = load_data_folder('ELETRONUCLEAR')
data_rjdf = load_data_folder('RJ-DF')
data_serra = load_data_folder('SERRA')
data_rjmgba = load_data_folder('RJ-MG-BA')
data_janeiro = load_data_folder('JANEIRO')

"""# **Análise Exploratória Preliminar**
Análise preliminar de cada base de dados: **ELETRONUCLEAR**, **RJ-DF** e **SERRA**. Conforme vai surgindo novos dados, vamos adicinando uma seção de tratamento para eles.

## 🛻**Eletronuclear**⚛️

- Dados coletados no pátio da Eletronuclear, usando os modelos de carro: **Van** e **Spin**.
- Teve uma coleta usando ônibus também. Porém, por esses dados estarem bem ruins, excluimos eles. Para isso, apenas verificamos se o dataset possui a coluna `pos_lat`, pois os dados dos ônibus são os únicos que tem.
"""

### Dados Eletronuclear
dfs = []
for file in data_eletro:

  df = pd.read_csv(file, sep=';')
  id = file.split('/')[-1]
  _,_,vehicle,_,_ = id.split('-')
  df = df.assign(id_route = id.replace('.csv',''),
                 vehicle = vehicle,
                 loc_coleta = 'eletronuclear')

  if 'pos_lat' not in df.columns: # dfs ruins dos ônibus (foram coletados usando datalogger)
    dfs.append(df)

de = pd.concat(dfs)
de.describe()

"""Ao olharmos os dados, percerbemos que as viagens `obd-17-van-cicuito-t2` e `obd-17-van-circuito-t1` tinha dados estranhos para velocidade (note o max de `vehicle_speed` acima). Assim, vamos excluir eles"""

dfruim = ['obd-17-van-cicuito-t2', 'obd-17-van-circuito-t1'] # dados ruins de velocidade dessas duas trips/route
de = de.query('id_route not in @dfruim')
de.describe()

"""Note que ainda tem dados estranhos de velocidade. O dataset `tabela_final-19-spin-trajeto-t1` apresentou outliers em velocidade, com alguns valores de 255 km/h. Assim, decidimos por deletar esses valores, mas preservar o restante da viagem"""

de = de.query('vehicle_speed != 255')

for trip in de.id_route.unique():
  df_cleaned = de.query(f'id_route == "{trip}"').dropna(subset=['lat', 'lon', 'vehicle_speed']).copy()
  plt.figure(figsize=(12, 8))
  hb = plt.hexbin(x=df_cleaned['lon'], y=df_cleaned['lat'], C=df_cleaned['vehicle_speed'],
                  gridsize=50, cmap='viridis', reduce_C_function=np.mean)
  plt.colorbar(hb, label='Média de Velocidade (km/h)')
  plt.xlabel('Longitude')
  plt.ylabel('Latitude')
  plt.title(f'Trajeto: {trip}')
  plt.grid(True)
  plt.show()

"""Gráfico da distribuição de velocidade dos dados coletados da Eletronuclear"""

fig, ax = plt.subplots(figsize=(12, 6))
ax.hist(de.vehicle_speed, bins=100)
ax.set_xlabel('Velocidade (km/h)')
ax.set_ylabel('Frequência')
ax.set_title('Histograma da Velocidade - dados da Eletro')
plt.show()

"""Vamos ver a proporção de velocidades iguais a 0 por vigem"""

de.groupby('id_route')['vehicle_speed'].apply(lambda x: (x == 0).sum() / len(x)*100)

new_de_dfs = []
for route_id in de['id_route'].unique():
    temp_df = de[de['id_route'] == route_id].copy()
    first_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.min()
    last_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.max()

    if pd.isna(first_non_zero_speed_idx) or pd.isna(last_non_zero_speed_idx):
        new_de_dfs.append(temp_df)
        print(f"Trip {route_id} não possui dados válidos.")
    else:
        new_de_dfs.append(temp_df.loc[first_non_zero_speed_idx:last_non_zero_speed_idx])

dev = pd.concat(new_de_dfs)
print("AGORA:", dev.shape, "ANTES:", de.shape)

"""Deletamos todas as linhas iniciais de cada trajeto com $v=0$. Agora vamos ver a proproção de zeros de velocidade"""

dev.groupby('id_route')['vehicle_speed'].apply(lambda x: (x == 0).sum() / len(x)*100)

fig, ax  = plt.subplots(figsize=(12,6))
ax.hist(dev.vehicle_speed, bins=100)
ax.set_xlabel('Velocidade (km/h)')
ax.set_ylabel('Frequência')
ax.set_title('Histograma da Velocidade - dados da Eletro')
plt.show()

"""---

## 🛣️**RJ-DF**🧑‍⚖️

Esses dados apresentam colunas com uma formatação diferente dos dados da ELETRO, vamos primeiro deixar iguais
"""

# colunas originais e como deve ser
cols_orig = ['Time (sec)', ' Latitude (deg)', ' Longitude (deg)',
              ' Vehicle speed (km/h)', ' Accel X (m/s²)', ' Accel Y (m/s²)',
              ' Accel Z (m/s²)', ' Engine RPM (RPM)', ' Mass air flow rate (g/s)',
              ' Absolute throttle position (%)', ' Fuel level input (%)',
              ' GPS Speed (km/h)', ' Fuel rate (l/hr)',
              ' Alcohol fuel percentage (%)', ' Engine fuel rate (l/hr)',
              ' Vehicle Fuel Rate (g/s)', ' Fuel Remaining (l)',
              ' Fuel Level Input A (%)', ' Fuel Level Input B (%)',
              ' Instant fuel economy (l/100 km)', ' Calculated load value (%)',
              ' Fuel rail pressure (kPa)',
              ' Fuel rail pressure relative to manifold vacuum (kPa)',
              ' Accelerator pedal position D (%)',
              ' Accelerator pedal position E (%)']

cols_rjdf = ['time','lat','lon','vehicle_speed','accel_x','accel_y','accel_z','engine_rpm',
              'mass_air_flow','absolute_throttle_pos','fuel_level','gps_speed',
              'fuel_rate','alcohol_fuel_percentage','engine_fuel_rate','vehicle_fuel_rate',
              'fuel_remaining','fuel_level_a','fuel_level_b','instant_fuel_economy',
              'calculated_load_value','fuel_rail_pressure_vacuum','fuel_rail_pressure',
              'accelerator_pedal_pos_d','accelerator_pedal_pos_e']

zip_cols = [(orig,col) for orig,col in zip(cols_orig,cols_rjdf)]

dfs_rjdf = []
for dado in data_rjdf:

  df = pd.read_csv(dado, skiprows=2) # isso aqui é pra resolver um problema de inicio dos dados.
  # muitos dfs começam a ter dados só a partir da 2 linha. Aqui estamos puxando eles

  if df.columns.to_list()!=cols_orig:
    df = pd.read_csv(dado, skiprows=1) # aqui estamos puxando os dados a partir da primeira linha mesmo
    # a condição é apenas fazendo a checam das colunas.

  df = df.rename(columns=dict(zip_cols)) # renomendo as colunas
  df = df.assign(id_route = dado.split('/')[-1].replace('.csv',''),
                 vehicle = 'nivus',
                 loc_coleta = 'rjdf')

  dfs_rjdf.append(df)

df_rjdf = pd.concat(dfs_rjdf) # juntando todas as Trips de RJ-DF em um só dataset
df_rjdf.describe() # veja as estatisticas

"""Histograma de velocidade dos dados **RJ-DF**"""

fig, ax = plt.subplots(figsize=(12,6))
ax.hist(df_rjdf.vehicle_speed, bins=100)
ax.set_xlabel('Velocidade (km/h)')
ax.set_ylabel('Frequência')
ax.set_title('Histograma da Velocidade - dados RJ-DF')
plt.show()

"""Proporção de velocidade zero por viagem"""

df_rjdf.groupby('id_route')['vehicle_speed'].apply(lambda x: (x == 0).sum() / len(x)*100)

"""A trip `CSVLog_20240920_092511` tem poucos pontos (116) e muitos deles são com $v=0$. Vamos excluir ela"""

df_rjdf = df_rjdf.query('id_route != "CSVLog_20240920_092511"')

"""Nenhuma viagem começa e nem termina com $v=0$:"""

new_drjdf_dfs = []
for route_id in df_rjdf['id_route'].unique():
    temp_df = df_rjdf[df_rjdf['id_route'] == route_id].copy()
    first_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.min()
    last_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.max()

    if pd.isna(first_non_zero_speed_idx) or pd.isna(last_non_zero_speed_idx):
        new_drjdf_dfs.append(temp_df)
        print(f"Trip {route_id} não possui dados válidos.")
    else:
        new_drjdf_dfs.append(temp_df.loc[first_non_zero_speed_idx:last_non_zero_speed_idx])

df_rjdf_v = pd.concat(new_drjdf_dfs)
print("AGORA:", df_rjdf_v.shape, "ANTES:", df_rjdf_v.shape)

"""---

## 🚙SERRA🪚
"""

dfs_serra = []
for dado in data_serra:
  df_serra = pd.read_csv(dado, skiprows=1)
  df_serra = df_serra.rename(columns=dict(zip_cols))
  df_serra = df_serra.assign(id_route = dado.split('/')[-1].replace('.csv',''),
                              vehicle = 'jetta',
                              loc_coleta = 'serra')

  dfs_serra.append(df_serra)

ds = pd.concat(dfs_serra)
ds.describe()

fig, ax = plt.subplots(figsize=(12,6))
ax.hist(ds.vehicle_speed, bins=100)
ax.set_xlabel('Velocidade (km/h)')
ax.set_ylabel('Frequência')
ax.set_title('Histograma da Velocidade - dados Serra')
plt.show()

"""Percentual de velocidades zero"""

ds.groupby('id_route')['vehicle_speed'].apply(lambda x: (x == 0).sum() / len(x)*100)

new_ds = []
for route_id in ds['id_route'].unique():
    temp_df = ds[ds['id_route'] == route_id].copy()
    first_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.min()
    last_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.max()

    if pd.isna(first_non_zero_speed_idx) or pd.isna(last_non_zero_speed_idx):
        new_ds.append(temp_df)
        print(f"Trip {route_id} não possui dados válidos.")
    else:
        new_ds.append(temp_df.loc[first_non_zero_speed_idx:last_non_zero_speed_idx])

dsv = pd.concat(new_ds)
print("AGORA:", dsv.shape, "ANTES:", dsv.shape)

"""---

# RJ-MG-BA
"""

cols_orig_rjmgba = [
    'Time (sec)',
    ' Intake manifold absolute pressure', ' Intake manifold absolute pressure (kPa)', ' Pressão absoluta do coletor de admissão (kPa)',
    ' Engine RPM', ' Engine RPM (RPM)', ' RPM do motor (RPM)',
    ' Vehicle speed', ' Vehicle speed (km/h)', ' Velocidade do veículo (km/h)',
    ' Intake air temperature', ' Intake air temperature (°C)', ' Temperatura do ar de admissão (°C)',
    ' Absolute throttle position', ' Absolute throttle position (%)', ' Posição absoluta do acelerador (%)',
    ' Fuel level input', ' Fuel level input (%)', ' Entrada do nível de combustível (%)',
    ' Fuel/Air commanded equivalence ratio', ' Relação de equivalência comandada por combustível/ar',
    ' Relative throttle position', ' Relative throttle position (%)', ' Posição relativa do acelerador (%)',
    ' Absolute throttle position B', ' Absolute throttle position B (%)', ' Posição absoluta do acelerador B (%)',
    ' Accelerator pedal position D', ' Accelerator pedal position D (%)', ' Posição D do pedal do acelerador (%)',
    ' Accelerator pedal position E', ' Accelerator pedal position E (%)', ' Posição do pedal do acelerador E (%)',
    ' Commanded throttle actuator control', ' Commanded throttle actuator control (%)', ' Controle do atuador do acelerador comandado (%)',
    ' Alcohol fuel percentage', ' Alcohol fuel percentage (%)', ' Porcentagem de álcool combustível (%)',
    ' Instant Fuel Economy', ' Instant Fuel Economy (l/100 km)', ' Economia de combustível instantânea (l/100 km)',
    ' Total Fuel Economy', ' Total Fuel Economy (l/100 km)', ' Economia total de combustível (l/100 km)',
    ' Fuel Rate', ' Fuel Rate (l/hr)', ' Taxa de combustível (l/hr)',
    ' Instant CO2 rate', ' Instant CO2 rate (g/km)', ' Taxa instantânea de CO2 (g/km)',
    ' Total CO2', ' Total CO2 (kg)',
    ' CO2 flow', ' CO2 flow (g/s)', ' Fluxo de CO2 (g/s)',
    ' Trip Distance', ' Trip Distance (km)', ' Distância da viagem (km)',
    ' Trip Fuel', ' Trip Fuel (l)', ' Combustível de viagem (l)',
    ' Trip Fuel Economy', ' Trip Fuel Economy (l/100 km)', ' Economia de combustível de viagem (l/100 km)',
    ' Hard Brake Count', ' Contagem de freios rígidos',
    ' Hard Accel Count', ' Contagem de aceleração difícil',
    ' Latitude (deg)',
    ' Longitude (deg)',
    ' Altitude (m)',
    ' Bearing (deg)', ' Rolamento (deg)',
    ' GPS Speed (km/h)', ' Velocidade do GPS (km/h)',
    ' Horz Accuracy (m)', ' Precisão Horz (m)',
    ' Accel X (m/s)', ' Accel X (m/s²)', ' Aceleração X (m/s²)',
    ' Accel Y (m/s²)', ' Acelere Y (m/s²)',
    ' Accel Z (m/s²)', ' Aceleração Z (m/s²)',
    ' Accel (Grav) X (m/s²)', ' Aceleração (Grav) X (m/s²)',
    ' Accel (Grav) Y (m/s²)', ' Aceleração (Grav) Y (m/s²)',
    ' Accel (Grav) Z (m/s²)', ' Aceleração (Grav) Z (m/s²)',
    ' Rotation Rate X', ' Rotation Rate X (deg/s)', ' Taxa de rotação X (deg/s)',
    ' Rotation Rate Y', ' Rotation Rate Y (deg/s)', ' Taxa de rotação Y (deg/s)',
    ' Rotation Rate Z', ' Rotation Rate Z (deg/s)', ' Taxa de rotação Z (deg/s)',
    ' Magnetometer X (µT)', ' Magnetometer X', ' Magnetômetro X (µT)',
    ' Magnetometer Y (µT)', ' Magnetometer Y', ' Magnetômetro Y (µT)',
    ' Magnetometer Z (µT)', ' Magnetometer Z', ' Magnetômetro Z (µT)'
]

cols_rjmgba_new = [
    'time',
    'intake_manifold_abs_pressure', 'intake_manifold_abs_pressure', 'intake_manifold_abs_pressure',
    'engine_rpm', 'engine_rpm', 'engine_rpm',
    'vehicle_speed', 'vehicle_speed', 'vehicle_speed',
    'intake_air_temp', 'intake_air_temp', 'intake_air_temp',
    'absolute_throttle_pos', 'absolute_throttle_pos', 'absolute_throttle_pos',
    'fuel_level', 'fuel_level', 'fuel_level',
    'fuel_air_equivalence_ratio', 'fuel_air_equivalence_ratio',
    'relative_throttle_pos', 'relative_throttle_pos', 'relative_throttle_pos',
    'absolute_throttle_pos_b', 'absolute_throttle_pos_b', 'absolute_throttle_pos_b',
    'accelerator_pedal_pos_d', 'accelerator_pedal_pos_d', 'accelerator_pedal_pos_d',
    'accelerator_pedal_pos_e', 'accelerator_pedal_pos_e', 'accelerator_pedal_pos_e',
    'commanded_throttle_actuator_control', 'commanded_throttle_actuator_control', 'commanded_throttle_actuator_control',
    'alcohol_fuel_percentage', 'alcohol_fuel_percentage', 'alcohol_fuel_percentage',
    'instant_fuel_economy', 'instant_fuel_economy', 'instant_fuel_economy',
    'total_fuel_economy', 'total_fuel_economy', 'total_fuel_economy',
    'fuel_rate', 'fuel_rate', 'fuel_rate',
    'instant_co2_rate', 'instant_co2_rate', 'instant_co2_rate',
    'total_co2', 'total_co2',
    'co2_flow', 'co2_flow', 'co2_flow',
    'trip_distance', 'trip_distance', 'trip_distance',
    'trip_fuel', 'trip_fuel', 'trip_fuel',
    'trip_fuel_economy', 'trip_fuel_economy', 'trip_fuel_economy',
    'hard_brake_count', 'hard_brake_count',
    'hard_accel_count', 'hard_accel_count',
    'lat',
    'lon',
    'altitude',
    'bearing', 'bearing',
    'gps_speed', 'gps_speed',
    'horz_accuracy', 'horz_accuracy',
    'accel_x', 'accel_x', 'accel_x',
    'accel_y', 'accel_y',
    'accel_z', 'accel_z',
    'accel_grav_x', 'accel_grav_x',
    'accel_grav_y', 'accel_grav_y',
    'accel_grav_z', 'accel_grav_z',
    'rotation_rate_x', 'rotation_rate_x', 'rotation_rate_x',
    'rotation_rate_y', 'rotation_rate_y', 'rotation_rate_y',
    'rotation_rate_z', 'rotation_rate_z', 'rotation_rate_z',
    'magnetometer_x', 'magnetometer_x', 'magnetometer_x',
    'magnetometer_y', 'magnetometer_y', 'magnetometer_y',
    'magnetometer_z', 'magnetometer_z', 'magnetometer_z'
]

zip_cols_rjmgba = [(orig, col) for orig, col in zip(cols_orig_rjmgba, cols_rjmgba_new)]

dfs_rjmgba = []
for dado in data_rjmgba:
    df_temp = pd.read_csv(dado, skiprows=1)
    current_cols = df_temp.columns.to_list()

    rename_dict = {}
    for orig_col, new_col in zip_cols_rjmgba:
        if orig_col in current_cols and orig_col not in rename_dict:
            rename_dict[orig_col] = new_col

    df_temp = df_temp.rename(columns=rename_dict)

    # mantem colunas não duplicadas
    df_temp = df_temp.loc[:, ~df_temp.columns.duplicated()]

    df_temp = df_temp.assign(id_route = dado.split('/')[-1].replace('.csv',''),
                             vehicle = 'Cruze e Jetta',
                             loc_coleta = 'rjmgba')
    dfs_rjmgba.append(df_temp)

df_rjmgba = pd.concat(dfs_rjmgba)
df_rjmgba.describe()

fig, ax = plt.subplots(figsize=(12,6))
ax.hist(df_rjmgba.vehicle_speed, bins=100)
ax.set_xlabel('Velocidade (km/h)')
ax.set_ylabel('Frequência')

new_df_rjmgba = []
for route_id in df_rjmgba['id_route'].unique():
    temp_df = df_rjmgba[df_rjmgba['id_route'] == route_id].copy()
    first_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.min()
    last_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.max()

    if pd.isna(first_non_zero_speed_idx) or pd.isna(last_non_zero_speed_idx):
        new_df_rjmgba.append(temp_df)
        print(f"Trip {route_id} não possui dados válidos.")
    else:
        new_df_rjmgba.append(temp_df.loc[first_non_zero_speed_idx:last_non_zero_speed_idx])

df_rjmgba_v = pd.concat(new_df_rjmgba)
print("AGORA:", df_rjmgba_v.shape, "ANTES:", df_rjmgba_v.shape)

"""# JANEIRO"""

dfs_janeiro = []
for dado in data_janeiro:
  df_temp = pd.read_csv(dado, skiprows=1)
  current_cols = df_temp.columns.to_list()

  rename_dict = {}
  for orig_col, new_col in zip_cols_rjmgba:
    if orig_col in current_cols and orig_col not in rename_dict:
      rename_dict[orig_col] = new_col

  df_temp = df_temp.rename(columns=rename_dict)
  df_temp = df_temp.loc[:, ~df_temp.columns.duplicated()]
  df_temp = df_temp.assign(id_route = dado.split('/')[-1].replace('.csv',''),
                                  vehicle = 'carro',
                                  loc_coleta = 'janeiro')
  dfs_janeiro.append(df_temp)

df_janeiro = pd.concat(dfs_janeiro)
df_janeiro.describe()

fig, ax = plt.subplots(figsize=(12,6))
ax.hist(df_janeiro.vehicle_speed, bins=100)
ax.set_xlabel('Velocidade (km/h)')
ax.set_ylabel('Frequência')

new_df_janeiro = []
for route_id in df_janeiro['id_route'].unique():
    temp_df = df_janeiro[df_janeiro['id_route'] == route_id].copy()
    first_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.min()
    last_non_zero_speed_idx = temp_df[temp_df['vehicle_speed'] != 0].index.max()

    if pd.isna(first_non_zero_speed_idx) or pd.isna(last_non_zero_speed_idx):
        new_df_janeiro.append(temp_df)
        print(f"Trip {route_id} não possui dados válidos.")
    else:
        new_df_janeiro.append(temp_df.loc[first_non_zero_speed_idx:last_non_zero_speed_idx])

df_janeiro_v = pd.concat(new_df_janeiro)
print("AGORA:", df_janeiro_v.shape, "ANTES:", df_janeiro_v.shape)

"""## ⚙ Alguns ajustes"""

def latlon_to_cartesian(latitudes, longitudes):
  '''
  Função que converte as coordenadas de latitude e longitude para coordenadas
  cartesianas.
  '''
  latitudes_rad = [math.radians(lat) for lat in latitudes]
  longitudes_rad = [math.radians(lon) for lon in longitudes]

  # Origem
  lat0 = latitudes_rad[0]
  lon0 = longitudes_rad[0]
  R = 6371000 # raio da Terra

  cartesian_coords = []
  for lat, lon in zip(latitudes_rad, longitudes_rad):
    if lat != lat0 or lon != lon0:
      x = R * (lon - lon0) * math.cos((lat + lat0) / 2)
      y = R * (lat - lat0)
      cartesian_coords.append((x, y))
    else:
      cartesian_coords.append((0, 0))

  return cartesian_coords

new_dfs = []

trips_eletro = dev.id_route.unique()
trips_rjdf = df_rjdf_v.id_route.unique()
trips_serra = dsv.id_route.unique()
trips_rjmgba = df_rjmgba_v.id_route.unique()
trips_janeiro = df_janeiro_v.id_route.unique()

trips = list(trips_eletro) + list(trips_rjdf) + list(trips_serra) + list(trips_rjmgba) + list(trips_janeiro)

for trip in trips:

  if trip in trips_eletro:
    df = dev.query(f'id_route == "{trip}"').copy()
  elif trip in trips_rjdf:
    df = df_rjdf_v.query(f'id_route == "{trip}"').copy()
  elif trip in trips_serra:
    df = dsv.query(f'id_route == "{trip}"').copy()
  elif trip in trips_rjmgba:
    df = df_rjmgba_v.query(f'id_route == "{trip}"').copy()
  elif trip in trips_janeiro:
    df = df_janeiro_v.query(f'id_route == "{trip}"').copy()

  df.dropna(subset=['lat', 'lon'], inplace = True)

  if len(set(['rjdf', 'serra', 'rjmgba', 'janeiro']) & set(df.loc_coleta.unique())) > 0:
    df['time_sec'] = df.time
  else:
    df.timestamp = pd.to_datetime(df.timestamp, format="mixed")
    df['time_sec'] = (df['timestamp'] - df['timestamp'].iloc[0]).dt.total_seconds()
    df = df.set_index('timestamp').sort_index()

  df['dt'] = df['time_sec'].diff().fillna(0)
  df['prev_speed'] = df['vehicle_speed'].shift(1).fillna(0)
  if 'fuel_rate' in df.columns:
    df.loc[(df['prev_speed'] == 0) & (df['fuel_rate']==0), 'dt'] = 0
  df.drop(columns='prev_speed', inplace=True)

  rows_prev, cols_pre = df.shape
  df = df[~((df['vehicle_speed'] < 1) & (df['accel_x'].abs() < 0.005) & (df['accel_y'].abs() < 0.005))]
  df = df.drop_duplicates(subset = ['lat','lon','vehicle_speed'], keep='last')
  df.reset_index(drop=True, inplace=True)

  coor = latlon_to_cartesian(df['lat'], df['lon'])
  x,y = zip(*coor)
  df = df.assign(x=x, y=y)

  for col in df.columns:
    if np.all(df[col] == 0) or df[col].notnull().sum() == 0:
      df.drop(columns=col, inplace=True)

  df = df.dropna(subset=['x', 'y'])
  new_dfs += [df.copy()]
  rows_now, cols_now = df.shape
  del df

  print(f'(Trip {len(new_dfs)}) Linhas removidas: {rows_prev - rows_now}, tinha {rows_prev}, agora tem {rows_now}. Numero de colunas antes: {cols_pre}, depois: {cols_now}')

df_all = pd.concat(new_dfs)
df_all.describe()

fig, ax = plt.subplots(figsize=(12,6))
ax.hist(df_all.vehicle_speed, bins=100)
ax.set_xlabel('Velocidade (km/h)')
ax.set_ylabel('Frequência')

df_all.to_parquet('eletro_rjdf_serra_rjmgba_janeiro.parquet', index=False)